### ISSUE TITLE
Please provide further details. What have you tried, what is your setup, what does not work?

### ISSUE THREAD

**Issue by Cryden** [OFFLINE-GmbH/oc-vite-plugin#10]
Please provide further details. What have you tried, what is your setup, what does not work?

_Originally posted by @tobias-kuendig in https://github.com/OFFLINE-GmbH/oc-vite-plugin/issues/9#issuecomment-1707783356_
            

Problem 1
    - Root composer.json requires offline/oc-vite-plugin ^2.0 -> satisfiable by offline/oc-vite-plugin[v2.0.0, ..., v2.0.5].
    - offline/oc-vite-plugin[v2.0.0, ..., v2.0.5] require laravel/framework ^9.0 -> found laravel/framework[v9.0.0-beta.1, ...,
9.x-dev] but it conflicts with your root composer.json require (^10.0).

**Comment by tobias-kuendig** [comment]
Are you using vite v2.0.6? We have added Laravel 10 support a few months ago:
https://github.com/OFFLINE-GmbH/oc-vite-plugin/commit/10e1b4320b382350fbf4ebab36fe77a0080a0e7c

```
composer require offline/oc-vite-plugin:^2.0.6
```

**Comment by Cryden** [comment]
- Root composer.json requires offline/oc-vite-plugin 2.0.6, it is satisfiable by offline/oc-vite-plugin[v2.0.6] from compose
r repo (https://repo.packagist.org) but offline/oc-vite-plugin[dev-main, v1.0.0, v1.0.1, v1.0.2, v2.0.0, ..., v2.0.5] from compo
ser repo (https://gateway.octobercms.com) has higher repository priority. The packages from the higher priority repository do no
t match your constraint and are therefore not installable. That repository is canonical so the lower priority repo's packages ar
e not installable. See https://getcomposer.org/repoprio for details and assistance.

**Comment by tobias-kuendig** [comment]
Looks like the marketplace did not get the latest update. Can you try again? The new version should now be available.

Thank you for the report!
