### ISSUE TITLE
Server errors

### ISSUE THREAD

**Issue by Cryden** [OFFLINE-GmbH/oc-vite-plugin#11]
[Thu Sep 14 09:29:13.745617 2023] [lsapi:warn] [pid ----- [client ------] [host -----] Backend log: PHP Deprecated:  Using ${var} in strings is deprecated, use {$var} instead in /-----/public_html/plugins/offline/vite/classes/Vite.php on line 156\n

**Comment by tobias-kuendig** [comment]
Thanks @Cryden, this is fixed in v2.0.7
