### ISSUE TITLE
ERR_ABORTED 404 (Not Found) in Vite 5.0

### ISSUE THREAD

**Issue by sergeitoroptsev** [OFFLINE-GmbH/oc-vite-plugin#14]
Vite has been updated to version 5.0 and plugin not working.

In dev mode assets return 404:

![image](https://github.com/OFFLINE-GmbH/oc-vite-plugin/assets/35667885/328cd372-4519-4488-b9eb-750d21f6a290)

Production too doesn't work (manifest now saves into .vite folder).

**Comment by tobias-kuendig** [comment]
Thank you for the report @sergeitoroptsev! Version 2.0.10 adds support for Vite 5.
