### ISSUE TITLE
File::isLocalPath check failes because of leading slash

### ISSUE THREAD

**Issue by marcogrueter** [OFFLINE-GmbH/oc-vite-plugin#16]
Hi offlines / @tobias-kuendig 

Sorry, I was a bit hasty with feedback. It works well for the site which was the reason for the PR, but I ran into troubles with another site. This time, I've got a parent theme, but the child theme has the assets (css, js) folder.

The `File::isLocalPath` fails in any case, imho because of the leading slash. It will become a "double slash" at the beginning when `base_path()` is applied.

Line in question:
https://github.com/OFFLINE-GmbH/oc-vite-plugin/blob/5c2a2186e1ecceb9bb009449ec9ee665af6913db/classes/Vite.php#L253

Quick fix was to remove the leading slash in the sprintf and before that check. I've also removed the slash in the sprintf inside the if condition (for good measure ;-)) and URL::to seems to handle it fine in any case.

Since I am not sure if this leads to any side effect later on and my proposed change is very small, I just created an issue this time around. Let me know if you want to have a PR!

Thank you very much for your support!

Kind regards und liebi grüess us em Kanton Zug ;-)

**Comment by tobias-kuendig** [comment]
Thank you for the feedback @marcogrueter! Indeed, starting the path with a slash will make it absolute, and therefore it won't be "local" to the project anymore.

Please give v2.0.12 a try.

**Comment by marcogrueter** [comment]
Yes, that does the trick! Thank you very much and have a great day.
